- hosts: workstation1
  remote_user: root
  become: true

  vars:
    z8_driver_url: https://ftp.hp.com/pub/softpaq/sp84001-84500/hp_drivercd_rhel7.4_sp84251.iso
    z8_driver_source: /vagrant/downloads/hp_drivercd_rhel7.4_sp84251.iso
    z8_driver_dest: /root/Downloads/hp_drivercd_rhel7.4_sp84251.iso
    z8_rgs_source: /vagrant/downloads/rgs76
    z8_rgs_dest: /root/Downloads
    ime_source: /vagrant/downloads/intel_management_engine_11.21
    ime_dest: /root/Downloads


  tasks:
  - name: check if driver exists on ansible host
    stat:
      path: "{{ z8_driver_source }}"
    delegate_to: ansible_control
    register: control_driver_stat

  - get_url:
      dest: "{{ z8_driver_source }}"
      url: "{{ z8_driver_url }}"
      mode: 0700
    delegate_to: ansible_control
    when: control_driver_stat.stat.exists == false

  - name: create Downloads path
    file:
      path: /root/Downloads
      state: directory

  - name: transfer z8 drivers
    copy:
      src: "{{ z8_driver_source }}"
      dest: "{{ z8_driver_dest }}"
      mode: 0700

  - name: create mount path
    file:
      path: /mnt/hp_drivercd
      state: directory

  - name: Install HP Drivers
    shell: |
      mount "{{ z8_driver_dest }}" /mnt/hp_drivercd
      cd /mnt/hp_drivercd
      ls
      cd /mnt/hp_drivercd/HP/scripts/
      ./install.sh --force
    register: mount_output

  - debug:
      msg: "{{ mount_output.stdout }}"

  - name: transfer z8 rgs
    copy:
      src: "{{ z8_rgs_source }}"
      dest: "{{ z8_rgs_dest }}"
      mode: 0700

  - name: transfer z8 ime
    copy:
      src: "{{ ime_source }}"
      dest: "{{ ime_dest }}"
      mode: 0700