# example
# ansible-playbook -i "$TF_VAR_inventory" secrets/modules/workstation/z8-deadlineuser.yaml --extra-vars "ansible_become_pass=sompass"
- hosts: workstation1
  remote_user: root
  become: true

  vars_prompt:
  - name: "my_password"
    prompt: "Enter password for new deadlineuser"
    private: yes
    encrypt: "sha512_crypt"
    confirm: yes
    salt_size: 7

  tasks:
  - stat:
      path: "/home/deadlineuser"
    register: result

  - debug:
      msg: "deadlineuser home directory exists already.  Will not create user or make any changes.  The password was not changed/set."
    when: result.stat.exists == true and result.stat.isdir == true

  - debug:
      msg: "deadlineuser home directory doesn't exist.  Will create user and set password."
    when: result.stat.exists == false

  - name: new group
    group:
      name: deadlineuser
      gid: 9001
      state: present

  - name: Create a login user
    user:
      name: deadlineuser
      uid: 9001
      password: "{{ my_password }}"
      groups: # Empty by default, here we give it some groups
        - wheel
        - deadlineuser
      state: present
      shell: /bin/bash # Defaults to /bin/bash
      system: no # Defaults to no
      createhome: yes # Defaults to yes
    when: result.stat.exists == false

  - name: Ensure group "syscontrol" exists
    group:
      name: syscontrol
      state: present
      gid: 9003
    become: true

  - name: adding existing user "{{ item }}" to group syscontrol
    user:
      name: "{{ item }}"
      groups: syscontrol
      append: yes
    with_items:
    - deadlineuser
    become: true