# ansible-playbook -i "$TF_VAR_inventory" secrets/modules/workstation/z8-mount-nfs.yaml --extra-vars "ansible_become_pass=sompass"
- hosts: workstation1
  remote_user: root
  become: true

  tasks:
  - name: create softnas mount point
    file: 
      path: "{{ item }}"
      state: directory
    become: yes
    with_items:
    - "/prod"
    - "/data"
    - "/aws_sydney_prod"
    - "/cairns_prod"

  - name: create softnas mount point
    file: 
      path: /data
      state: directory
    become: yes

  - name: insert marker start
    lineinfile:
      path: /etc/fstab
      insertafter: "^#?/dev/mapper.*$"
      line: "# BEGIN ANSIBLE MANAGED BLOCK"
      backup: yes

  - name: insert marker end
    lineinfile:
      path: /etc/fstab
      insertafter: "# BEGIN ANSIBLE MANAGED BLOCK"
      line: "# END ANSIBLE MANAGED BLOCK"
      create: true
      backup: yes
 
  - name: insert/update block in /etc/fstab
    blockinfile:
      path: /etc/fstab
      marker: "# {mark} ANSIBLE MANAGED BLOCK 192.168.92.11"
      backup: yes
      content: |
        
        192.168.92.11:/data /data nfs defaults,_netdev,rsize=8192,wsize=8192,timeo=14,intr 0 0
        192.168.92.11:/prod /cairns_prod nfs defaults,_netdev,rsize=8192,wsize=8192,timeo=14,intr 0 0
        /cairns_prod /prod none defaults,bind 0 0

  - name: insert/update block in /etc/sysconfig/network
    blockinfile:
      path: /etc/sysconfig/network
      marker: "# {mark} ANSIBLE MANAGED BLOCK delay"
      backup: yes
      content: |
        NETWORKDELAY=20

  - name: mount all changes to fstab
    command: mount -a
    become: true