- hosts: workstation.firehawkvfx.com
  remote_user: root
  become: true

  vars:
    vbox_url: https://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo
    vbox_dest: /etc/yum.repos.d/virtualbox.repo
    vagrant_url: https://releases.hashicorp.com/vagrant/2.2.4/vagrant_2.2.4_x86_64.rpm
    vagrant_dest: /var/tmp/vagrant_2.2.4_x86_64.rpm

  tasks:
  - shell: |
      sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
      sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
  
  - get_url:
      url: "{{ vbox_url }}"
      dest: "{{ vbox_dest }}"
  
  - name: install packages, ansible, code, git.
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - ansible
      - code
      - git

  - name: upgrade all packages
    yum:
      name: '*'
      state: latest

  # steps required for virtual box https://www.if-not-true-then-false.com/2010/install-virtualbox-with-yum-on-fedora-centos-red-hat-rhel/

  - name: install dependencies for virtual box.
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - binutils 
      - gcc 
      - make 
      - patch 
      - libgomp 
      - glibc-headers 
      - glibc-devel 
      - kernel-headers 
      - kernel-devel 
      - dkms
      - VirtualBox-6.0
  
  - get_url:
      url: "{{ vagrant_url }}"
      dest: "{{ vagrant_dest }}"
      mode: 700

  - name: vagrant
    yum:
      name: "{{ vagrant_dest }}"
      state: present